FROM python:3.13-slim

RUN pip install --no-cache-dir uv

RUN uv tool install opencode@latest

ENV PATH="/root/.local/bin:${PATH}"

EXPOSE 8080

WORKDIR /data

CMD ["opencode", "serve", "--port", "8080", "--print-logs", "--pure", "--host", "0.0.0.0"]